#!/bin/sh

# Git
ln -sf ~/dotfiles-min/.config/git/ ~/.config

# Vim
ln -sf ~/dotfiles-min/.config/vim/.vimrc ~/.vimrc

# Neovim
ln -sf ~/dotfiles-min/.config/nvim/ ~/.config

# Fish
ln -sf ~/dotfiles-min/.config/fish/ ~/.config
